definitions:
  models.Event:
    properties:
      city:
        example: SuperCity
        type: string
      comment:
        example: Super exciting comment.
        type: string
      date:
        example: "2021-10-31T19:00:00.000Z"
        type: string
      location:
        example: SuperLocation
        type: string
      title:
        example: ExcitingTitle
        type: string
      type:
        example: concert
        type: string
      url:
        example: http://link.to/concert/page
        type: string
    required:
    - city
    - date
    - location
    - title
    - type
    - url
    type: object
info:
  contact: {}
paths:
  /api/events:
    get:
      consumes:
      - application/json
      description: Get all events.
      parameters:
      - description: title search string
        in: query
        name: title
        type: string
      - description: location search string
        in: query
        name: location
        type: string
      - description: city search string
        in: query
        name: city
        type: string
      - description: page number
        in: query
        name: page
        type: integer
      - description: page size
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
      summary: Get all events.
      tags:
      - events
    post:
      consumes:
      - application/json
      description: Add a new event.
      parameters:
      - description: Event Info
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses:
        "400":
          description: Failed to parse body
          schema:
            type: string
        "500":
          description: Failed to insert event
          schema:
            type: string
      summary: Add a new event.
      tags:
      - events
  /api/events/today/slack:
    post:
      consumes:
      - application/json
      description: Get today's events.
      produces:
      - application/json
      responses:
        "200":
          description: A json with the results
          schema:
            type: string
      summary: Get today's events.
      tags:
      - events
swagger: "2.0"
