definitions:
  models.Event:
    properties:
      city:
        example: SuperCity
        type: string
      comment:
        example: Super exciting comment.
        type: string
      date:
        example: "2021-10-31T19:00:00.000Z"
        type: string
      location:
        example: SuperLocation
        type: string
      sourceUrl:
        example: http://link.to/source
        type: string
      title:
        example: ExcitingTitle
        type: string
      type:
        example: concert
        type: string
      url:
        example: http://link.to/concert/page
        type: string
    required:
    - city
    - date
    - location
    - sourceUrl
    - title
    - type
    - url
    type: object
info:
  contact: {}
paths:
  /api/events:
    delete:
      consumes:
      - application/json
      description: Delete events.
      parameters:
      - description: sourceUrl string
        in: query
        name: sourceUrl
        type: string
      - description: datetime string
        in: query
        name: datetime
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A success message
          schema:
            type: string
        "500":
          description: Failed to delete events
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Delete events.
      tags:
      - events
    get:
      consumes:
      - application/json
      description: This endpoint returns all events matching the search terms. Note
        that only events from today on will be returned, ie no past events.
      parameters:
      - description: title search string
        in: query
        name: title
        type: string
      - description: location search string
        in: query
        name: location
        type: string
      - description: city search string
        in: query
        name: city
        type: string
      - description: date search string
        in: query
        name: date
        type: string
      - description: page number
        in: query
        name: page
        type: integer
      - description: page size
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
        "404":
          description: No events found
          schema:
            type: string
      summary: Get all events.
      tags:
      - events
    post:
      consumes:
      - application/json
      description: Add new events to the database.
      parameters:
      - description: Event Info
        in: body
        name: message
        required: true
        schema:
          items:
            $ref: '#/definitions/models.Event'
          type: array
      produces:
      - application/json
      responses:
        "400":
          description: Failed to parse body
          schema:
            type: string
        "500":
          description: Failed to insert events
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Add new events.
      tags:
      - events
  /api/events/{field}:
    get:
      description: This endpoint returns all distinct values for the given field.
        Note that past events are not considered for this query.
      parameters:
      - description: field name, can only be location or city
        in: path
        name: field
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Failed to retrieve values
          schema:
            type: string
      summary: Get distinct field values.
      tags:
      - events
  /api/events/today/slack:
    post:
      consumes:
      - application/json
      description: This endpoint returns today's events in a format that slack needs
        for its slash command. Currently, Zurich is hardcoded as city (will be changed).
      produces:
      - application/json
      responses:
        "200":
          description: A json with the results
          schema:
            type: string
      summary: Get today's events.
      tags:
      - events
swagger: "2.0"
